#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

const int WINDOW_WIDTH = 1000;
const int WINDOW_HEIGHT = 600;
const int GROUND_HEIGHT = 500;
const int TIME_ALLOWED = 60;

#endif // CONSTANTS_H_INCLUDED
